# Generated by Django 3.2.4 on 2023-01-21 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_details_faculty_details_subject_handled_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_details',
            name='mail',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 21, 15, 28, 52, 660784, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 21, 15, 28, 52, 658784, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=200),
        ),
    ]
