# Generated by Django 4.0.1 on 2023-01-23 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20230123_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='class_image',
            field=models.ImageField(default='images/Screenshot_3.png', upload_to='classroom_photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 23, 13, 27, 32, 586466, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 23, 13, 27, 32, 584466, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 23, 13, 27, 32, 587465, tzinfo=utc)),
        ),
    ]
