# Generated by Django 3.2.4 on 2023-01-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_classrooms_class_image_alter_details_date_and_more'),
        ('base', '0009_auto_20230123_1925'),
    ]

    operations = [
    ]
