# Generated by Django 3.2.4 on 2023-01-31 03:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20230124_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.faculty_details'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 31, 3, 28, 46, 770877, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 31, 3, 28, 46, 770877, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 31, 3, 28, 46, 778886, tzinfo=utc)),
        ),
    ]
