# Generated by Django 3.2.4 on 2023-01-31 04:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20230131_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_enrolled',
            name='id',
        ),
        migrations.AddField(
            model_name='classrooms',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 31, 4, 35, 20, 842896, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='class_enrolled',
            name='class_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 31, 4, 35, 20, 842896, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 31, 4, 35, 20, 842896, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 31, 4, 35, 20, 842896, tzinfo=utc)),
        ),
    ]
