# Generated by Django 3.2.4 on 2023-01-31 03:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20230131_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 31, 3, 33, 44, 41367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 31, 3, 33, 44, 41367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 31, 3, 33, 44, 33366, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 31, 3, 33, 44, 41367, tzinfo=utc)),
        ),
    ]
