# Generated by Django 3.0.5 on 2023-03-02 16:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20230302_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=datetime.datetime(2023, 3, 2, 16, 56, 20, 785167, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 2, 16, 55, 46, 524103, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 2, 16, 55, 46, 524103, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 2, 16, 55, 46, 524103, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='ebooks')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Course')),
            ],
        ),
    ]
