# Generated by Django 3.0.5 on 2023-03-18 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20230302_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('subject_states', models.CharField(max_length=50)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
