# Generated by Django 3.0.5 on 2023-03-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20230318_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='status',
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
