# Generated by Django 3.0.5 on 2023-03-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20230319_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='none', max_length=40),
            preserve_default=False,
        ),
    ]
