# Generated by Django 3.0.5 on 2023-03-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_enrolled',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
