# Generated by Django 3.0.5 on 2023-03-19 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_class_enrolled_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookForClass',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Class_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='ebooks')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.NoteCourse')),
            ],
        ),
    ]
