# Generated by Django 3.0.5 on 2023-03-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_ebookforclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebookforclass',
            name='Class_id',
            field=models.CharField(max_length=50),
        ),
    ]
