# Generated by Django 3.0.5 on 2023-03-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20230320_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookforclass',
            name='cover_image',
            field=models.CharField(default='uel', max_length=100),
            preserve_default=False,
        ),
    ]
